// Generated by scripts/build-fps-bridge.cjs --record. See native/fps-bridge/README.md.
export const FPS_BRIDGE_MANIFEST = Object.freeze({
  version: 1,
  filename: "fps-bridge.exe",
  size: 28160,
  sha256: "28507fe29697ec4cde50c7bc9cb88a2a2d155cd9589c80bf65c81f248f090977",
});
