// Generated by scripts/build-fps-bridge.cjs --record. See native/fps-bridge/README.md.
export const FPS_BRIDGE_MANIFEST = Object.freeze({
  version: 3,
  filename: "fps-bridge.exe",
  size: 36864,
  sha256: "12db0203a736f56b51c424c3ad26d2efbbdae4b5b870b8f62df639b024e182ba",
});
export const FPS_STEAM_ARTIFACTS = Object.freeze([
  {
    filename: "steam.exe",
    resource: "steam64.exe",
    tag: "yaagl-steam-347fbd2",
    size: 111304,
    sha256: "0424339444c54bf1f9fdbadf12e4e2c90ceef41d987fe573b93f5f2ebfd8a657",
  },
  {
    filename: "lsteamclient.dll",
    resource: "lsteamclient64.dll",
    tag: "yaagl-steam-347fbd2",
    size: 5560872,
    sha256: "af50ed0d952ef98d99d4d3ff67b4836b545c9403894430fca31969f9f630637b",
  },
]);
